deploy:ses:master:
  rules:
    - if: $CI_COMMIT_BRANCH == 'master'
  script:
    - yarn node apps/react-templates/lib/deploy.js
  stage: deploy
  dependencies:
    - setup
    - build
  needs:
    - setup
    - build
  variables:
    SLS_STAGE: production
    APP_ORIGIN: https://$APP_ORIGIN
