name: Sync Algolia with Squidex
on:
  workflow_dispatch:
    inputs:
      entity:
        required: false
        type: choice
        description: Choose which entity to sync
        default: all
        options:
          - users
          - research-outputs
          - external-authors
          - events
          - all
      environment-name:
        required: true
        type: environment
        description: Choose which environment to sync
        default: Branch
      contentful-environment-id:
        required: true
        type: string
        description: The contentful environment to sync from
        default: Development
      pr-number:
        required: false
        type: string
        description: The PR number to run for

jobs:
  setup:
    runs-on: ubuntu-latest
    environment: Branch
    outputs:
      crn-contentful-env: ${{ steps.get-contentful-state.outputs.contentful-env }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup
        id: setup
        uses: ./.github/actions/setup-environment
        with:
          environment-name: Branch
          pr-number: ${{ github.event.inputs.pr-number }}
      - name: Get Contentful Environment state
        id: get-contentful-state
        uses: ./.github/actions/contentful-checks
        with:
          contentful-space-id: ${{ steps.setup.outputs.crn-contentful-space-id }}
          contentful-master-env: ${{ steps.setup.outputs.contentful-environment }}
          contentful-token: ${{ secrets.CONTENTFUL_MANAGEMENT_TOKEN }}
          max-contentful-envs: ${{ steps.setup.outputs.max-contentful-envs }}
          contentful-environment-id: ${{ steps.setup.outputs.crn-contentful-env-id }}
          app: crn
  algolia:
    uses: ./.github/workflows/reusable-algolia-sync.yml
    with:
      environment-name: ${{ github.event.inputs.environment-name }}
      entity: ${{ github.event.inputs.entity }}
      pr-number: ${{ github.event.inputs.pr-number }}
      contentful-environment-id: ${{ github.event.inputs.contentful-environment-id }}
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      CRN_SQUIDEX_CI_CLIENT_SECRET: ${{ secrets.CRN_SQUIDEX_CI_CLIENT_SECRET }}
      CRN_CONTENTFUL_ACCESS_TOKEN: ${{ secrets.CRN_CONTENTFUL_ACCESS_TOKEN }}
      CONTENTFUL_MANAGEMENT_TOKEN: ${{ secrets.CONTENTFUL_MANAGEMENT_TOKEN }}

  notify_failure:
    runs-on: ubuntu-latest
    needs: [algolia]
    if: ${{ failure() && github.event.inputs.environment-name=='Production' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: ./.github/actions/slack/
        with:
          message: Algolia Prod Sync
          webhook: ${{ env.SLACK_WEBHOOK }}
          status: failure
