name: Transform Privacy Policy
on:
  workflow_dispatch:
    inputs:
      environment-name:
        required: true
        description: The environment name
        type: choice
        options:
          - Branch
          - Development
          - Production
      application:
        required: true
        description: Select which application contentful space to target
        type: choice
        options:
          - CRN
          - GP2
      contentful-env:
        required: true
        type: string
        description: Choose the Contentful environment to transform privacy policy

jobs:
  transform_privacy_policy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment-name }}
    container:
      image: ghcr.io/yldio/asap-hub/node-python-sq:7b77d99657ab3718ed548ba366ffbcbb15315fd8
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup
        id: setup
        uses: ./.github/actions/setup-environment
        with:
          environment-name: ${{ inputs.environment-name }}
      - name: Set Contentful Space Id
        run: |
          if [ "${{ inputs.application }}" = "GP2" ]; then
            echo "CONTENTFUL_SPACE_ID=${{ steps.setup.outputs.gp2-contentful-space-id }}" >> $GITHUB_ENV
          else
            echo "CONTENTFUL_SPACE_ID=${{ steps.setup.outputs.crn-contentful-space-id }}" >> $GITHUB_ENV
          fi
      - name: Transform Privacy Policy
        run: |
          yarn workspace @asap-hub/contentful transform-privacy-policy
        env:
          CONTENTFUL_MANAGEMENT_ACCESS_TOKEN: ${{ secrets.CONTENTFUL_MANAGEMENT_TOKEN }}
          CONTENTFUL_ENV_ID: ${{ inputs.contentful-env }}

  notify_failure:
    runs-on: ubuntu-latest
    needs: [transform_privacy_policy]
    if: ${{ failure() && inputs.environment-name=='Production' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: ./.github/actions/slack/
        with:
          message: Transform Privacy Policy failed
          webhook: ${{ secrets.SLACK_WEBHOOK }}
          status: failure
