name: Migrate impact and categories
on:
  workflow_dispatch:

jobs:
  migrate_impact_categories:
    runs-on: ubuntu-latest
    environment: Production
    container:
      image: ghcr.io/yldio/asap-hub/node-python-sq:7b77d99657ab3718ed548ba366ffbcbb15315fd8
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup
        id: setup
        uses: ./.github/actions/setup-environment
        with:
          environment-name: Production
      - name: Run Impact and Categories Migration
        run: |
          yarn workspace @asap-hub/contentful migrate-impact-categories
        env:
          CONTENTFUL_MANAGEMENT_ACCESS_TOKEN: ${{ secrets.CONTENTFUL_MANAGEMENT_TOKEN }}
          CONTENTFUL_SPACE_ID: ${{ steps.setup.outputs.crn-contentful-space-id }}
          CONTENTFUL_ENV_ID: Production

  notify_failure:
    runs-on: ubuntu-latest
    needs: [migrate_impact_categories]
    if: ${{ failure() }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: ./.github/actions/slack/
        with:
          message: Impact and categories migration failed
          webhook: ${{ secrets.SLACK_WEBHOOK }}
          status: failure
